name: Michael Paquier - PostgreSQL hacker
description: Blog about PostgreSQL and other things
url: http://paquier.xyz
kramdown:
gems: [jekyll-paginate]
highlighter: rouge
permalink: /:categories/:title/
paginate: 10
paginate_path: page:num
tag_title_prefix: 'Posts tagged as &ldquo;'
tag_title_suffix: '&ldquo;'
tag_dir: 'tag'
